SDL-02338 update per proposal revision
LuxoftSDL/sdl_hmi_integration_guidelines pull request #13
Opened 2021-02-08 11:31 UTC by KhrystynaDubovyk

2021-02-08 14:37 UTC, LitvinenkoIra approved these changes

2021-02-09 13:25 UTC, ychernysheva requested changes

2021-02-09 13:25 UTC, ychernysheva commented on docs/BasicCommunication/OnSystemCapabilityUpdated/index.md
> -5. HMI may send `KeyboardCapabilities` within OnSystemCapabilityUpdated notification which may include `maskInputCharactersSupported`, `supportedKeyboardLayouts` and `configurableKeys` parameters.
There is no separate `configurableKeys` param now, after revision it's a part of `supportedKeyboards` struct.

2021-02-09 13:25 UTC, ychernysheva commented on docs/BasicCommunication/OnSystemCapabilityUpdated/index.md
> -2. In case HMI sends OnSystemCapabilityUpdated notification with `KeyboardCapabilities`, `supportedKeyboardLayouts`  and without information about `numConfigurableKeys`, SDL would provide `KeyboardCa
There is no case when it may be info about `supportedKeyboards`, but no info about `numConfigurableKeys`, because now `numConfigurableKeys` and `keyboardLayout` are mandatory fields of `KeyboardLayoutCapability` struct (`supportedKeyboards`).

That's why if we have some info about supported layouts, we will also have info about corresponding numKeys. So now not SDL, but HMI would provide `KeyboardCapabilities` to app with `numConfigurableKeys` set to zero.

2021-02-09 13:49 UTC, KhrystynaDubovyk commented on docs/BasicCommunication/OnSystemCapabilityUpdated/index.md
> -5. HMI may send `KeyboardCapabilities` within OnSystemCapabilityUpdated notification which may include `maskInputCharactersSupported`, `supportedKeyboardLayouts` and `configurableKeys` parameters.
thank you, updated in https://github.com/LuxoftSDL/sdl_hmi_integration_guidelines/pull/13/commits/7bf061ddbcf495a14f2f6ed2582e44402fbeec4b

2021-02-09 13:52 UTC, KhrystynaDubovyk commented on docs/BasicCommunication/OnSystemCapabilityUpdated/index.md
> -2. In case HMI sends OnSystemCapabilityUpdated notification with `KeyboardCapabilities`, `supportedKeyboardLayouts`  and without information about `numConfigurableKeys`, SDL would provide `KeyboardCa
@ychernysheva, thanks.
I guess this point is worth removing. Since SDL would have to perform its regular function, i.e. transferring what was received from HMI to an app.
What would you say?

2021-02-09 14:25 UTC, ychernysheva commented on docs/BasicCommunication/OnSystemCapabilityUpdated/index.md
> -2. In case HMI sends OnSystemCapabilityUpdated notification with `KeyboardCapabilities`, `supportedKeyboardLayouts`  and without information about `numConfigurableKeys`, SDL would provide `KeyboardCa
Yes, I agree.

2021-02-09 16:02 UTC, KhrystynaDubovyk commented on docs/BasicCommunication/OnSystemCapabilityUpdated/index.md
> -2. In case HMI sends OnSystemCapabilityUpdated notification with `KeyboardCapabilities`, `supportedKeyboardLayouts`  and without information about `numConfigurableKeys`, SDL would provide `KeyboardCa
done in https://github.com/LuxoftSDL/sdl_hmi_integration_guidelines/pull/13/commits/b1deb58035d1e37d1bec2c0ab2b6f8e991e9c525

2021-02-09 16:09 UTC, merged